### ISSUE TITLE
TypeScript 相关内容

### ISSUE THREAD

**Issue by whosDL** [HopeStudio/Learning-Resources#1]
TypeScript 入门教程（中文）：https://ts.xcatliu.com/
TypeScript 官方文档：https://www.typescriptlang.org/
TypeScript 练习题（从入门到进阶）：https://github.com/typescript-exercises/typescript-exercises
TS to JS：https://www.typescriptlang.org/play/
@changchangge

**Comment by leiyu-97** [comment]
是不是可以直接提个PR

**Comment by whosDL** [comment]
> 是不是可以直接提个PR

工作电脑没用github，不太方便 -_-!
